name: newsapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.2 <4.0.0"  # ✅ Corrected SDK format

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.3.2  # ✅ Moved outside incorrect nesting
  cupertino_icons: ^1.0.8  # ✅ Placed correctly inside dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true